#!/bin/bash
year=$1
for d in $(ls /data/gup-imports/files/scopus | grep $year) ; 
   #do echo "$d"; 
   do docker-compose exec gup-imports bash -c 'python3 /data/scripts/index_scopus_docs.py -d /data/files/'"$d"'' >> /var/tmp/gup-scopus-indexing.log ;
done

