#!/bin/bash

d1=$1
d2=$(date -I -d "$d1 + 1 week")

while [ "$d1" != $d2 ]; do
  docker exec gup-imports-gup-imports-1 bash -c 'python3 /data/scripts/get-swepub-docs.py -d '"$d1"' -o /data/files/swepub-raw -a $INDEX_MANAGER_API_KEY' >> /var/tmp/gup-swepub.log 2>&1 
  d1=$(date -I -d "$d1 + 1 day")
done

