#!/bin/bash

d1=$1
d2=$(date -I -d "$d1 + 1 year")

while [ "$d1" != $d2 ]; do
  docker-compose exec gup-imports bash -c 'python3 /data/scripts/get-wos-docs.py -d '"$d1"' -o /data/files/wos-raw -a $WOS_API_KEY' >> /var/tmp/gup-wos.log 
  d1=$(date -I -d "$d1 + 1 day")
done

