#!/bin/bash

d1=$1
d2=$(date -I -d "$d1 + 4 year")

while [ "$d1" != $d2 ]; do
  docker exec gup-imports_gup-imports_1 bash -c 'python3 /data/scripts/complete-identifiers.py -d /data/files/scopus-normalised/'"$d1"'' >> /var/tmp/gup-scopus-matched-result.txt
  d1=$(date -I -d "$d1 + 1 day")
done

