#!/bin/bash

d1=$1
d2=$(date -I -d "$d1 + 5 week")

while [ "$d1" != $d2 ]; do
  docker exec gup-imports-gup-imports-1 bash -c 'python3 /data/scripts/transform-swepub-docs.py -s /data/files/swepub-raw/'"$d1"' -d /data/files/swepub-normalised/'"$d1"'' >> /var/tmp/gup-swepub-normalising.log
  d1=$(date -I -d "$d1 + 1 day")
done

