#!/usr/bin/env bash

d1=$1
d2=$(date -I -d "$d1 + 3 year")

while [ "$d1" != $d2 ]; do
  docker exec gup-imports-gup-imports-1 bash -c 'python3 /data/scripts/put-to-gup-admin.py -d /data/files/wos-normalised/'"$d1"' -u $INDEX_MANAGER_LAB_URL -a $INDEX_MANAGER_LAB_API_KEY' >> /var/tmp/gup-wos-put-to-gup-admin-index-manager-lab.log
  d1=$(date -I -d "$d1 + 1 day")
done

