#!/bin/bash

d1=$1
d2=$(date -I -d "$d1 + 4 year")

while [ "$d1" != $d2 ]; do
  docker exec gup-imports-gup-imports-1 bash -c 'python3 /data/scripts/transform-scopus-docs.py -s /data/files/scopus-raw/'"$d1"' -d /data/files/scopus-normalised/'"$d1"'' >> /var/tmp/gup-scopus-normalising.log
  d1=$(date -I -d "$d1 + 1 day")
done

