services:
  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    restart: always
    environment:
      xpack.security.enabled: "false"
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - ${ELASTIC_HOST_PORT}:${ELASTIC_PORT}
    volumes:
      - ${ELASTIC_HOST_DATA_DIR}:/usr/share/elasticsearch/data
  gup-imports:
    image: docker.ub.gu.se/gup-imports:${GUP_IMPORTS_IMAGE_VERSION}
    restart: always
    environment:
      - SCOPUS_API_KEY=${SCRIPT_SCOPUS_API_KEY}
      - WOS_API_KEY=${SCRIPT_WOS_API_KEY}
      - INDEX_MANAGER_LAB_URL=${SCRIPT_INDEX_MANAGER_LAB_URL}
      - INDEX_MANAGER_LAB_API_KEY=${SCRIPT_INDEX_MANAGER_LAB_API_KEY}
      - INDEX_MANAGER_STAGING_URL=${SCRIPT_INDEX_MANAGER_STAGING_URL}
      - INDEX_MANAGER_STAGING_API_KEY=${SCRIPT_INDEX_MANAGER_STAGING_API_KEY}
      - INDEX_MANAGER_URL=${SCRIPT_INDEX_MANAGER_URL}
      - INDEX_MANAGER_API_KEY=${SCRIPT_INDEX_MANAGER_API_KEY}
    tty: true
    volumes:
      - ${HOST_SCOPUS_RAW_JSON_FILES_DIR}:/data/files/scopus-raw
      - ${HOST_WOS_RAW_JSON_FILES_DIR}:/data/files/wos-raw
      - ${HOST_SCOPUS_NORMALISED_JSON_FILES_DIR}:/data/files/scopus-normalised
      - ${HOST_WOS_NORMALISED_JSON_FILES_DIR}:/data/files/wos-normalised
      - ${HOST_SCRIPT_FILES_DIR}:/data/scripts
  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    volumes:
      - ${KIBANA_HOST_DATA_DIR}:/usr/share/kibana/data
    restart: always
    environment:
      SERVER_NAME: ${KIBANA_SERVER_NAME}
      SERVER_PUBLICBASEURL: ${KIBANA_PUBLIC_URL}
      ELASTICSEARCH_HOSTS: ${KIBANA_ELASTICSEARCH_HOSTS}
      SERVER_BASEPATH: ${KIBANA_SERVER_BASEPATH}
#      SERVER_HOST=0.0.0.0
      SERVER_REWRITEBASEPATH: "true"
    ports:
      - ${KIBANA_HOST_PORT}:${KIBANA_PORT}
