version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    restart: always
    environment:
      xpack.security.enabled: "false"
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - ${ELASTIC_HOST_PORT}:${ELASTIC_PORT}
    volumes:
      - ${ELASTIC_HOST_DATA_DIR}:/usr/share/elasticsearch/data
  gup-imports:
    image: docker.ub.gu.se/gup-imports:${GUP_IMPORTS_IMAGE_VERSION}
    restart: always
    environment:
      - SCOPUS_API_KEY=${SCRIPT_SCOPUS_API_KEY}
      - INDEX_MANAGER_LAB_URL=${SCRIPT_INDEX_MANAGER_LAB_URL}
      - INDEX_MANAGER_LAB_API_KEY=${SCRIPT_INDEX_MANAGER_LAB_API_KEY}
      - INDEX_MANAGER_STAGING_URL=${SCRIPT_INDEX_MANAGER_STAGING_URL}
      - INDEX_MANAGER_STAGING_API_KEY=${SCRIPT_INDEX_MANAGER_STAGING_API_KEY}
      - INDEX_MANAGER_URL=${SCRIPT_INDEX_MANAGER_URL}
      - INDEX_MANAGER_API_KEY=${SCRIPT_INDEX_MANAGER_API_KEY}
    tty: true
    volumes:
      - ${HOST_SCOPUS_RAW_JSON_FILES_DIR}:/data/files/scopus-raw
      - ${HOST_SCOPUS_NORMALISED_JSON_FILES_DIR}:/data/files/scopus-normalised
      - ${HOST_SCRIPT_FILES_DIR}:/data/scripts
